chore: update spotless-plugin to 3.0.0 and palantir-java-format to 2.74.0
Current configuration yields `NoSuchMethodError` upon compilation when using java 25,
which is now fixed in `palantir-java-format:2.71.0`:
https://github.com/palantir/palantir-java-format/pull/1305

That only change would be sufficient, but I updated the palantir version to `2.74.0`
and also the spotless plugin to `3.0.0` to comply with this change in the original repo:
https://github.com/feature-tracker/feature-service/commit/1e2fca6a7d7d74278b3222ffe729754b517c6613

Also fixes readme that still mentioned java 21 as prerequisite, when in fact it is now java 24.